index:
    path: /
    controller: App\Controller\HomeController::index

washer-search:
    path: /chercher-une-machine
    controller: App\Controller\WasherController::search

washer-propose:
    path: /proposer-ses-services
    controller: App\Controller\WasherController::propose

user-register:
    path: /inscription
    controller: App\Controller\UserController::register

user-login:
    path: /connexion
    controller: App\Controller\UserController::login